### ISSUE TITLE
DNSCrypt config in a docker volume

### ISSUE THREAD

**Issue by modem7** [vgist/dockerfiles#11]
Is there any way I could have my toml file in a docker volume rather than on the main host at all for DNSCrypt?

Not quite sure how I would reference the config directory at all?

Thanks!

**Comment by aueu** [comment]
`-v /your/dnscrypt-proxy.toml :/etc/dnscrypt-proxy/dnscrypt-proxy.toml`

**Comment by modem7** [comment]
Perfect, thank you!
