### ISSUE TITLE
Transmission image isn't updated on Docker Hub

### ISSUE THREAD

**Issue by elisimpson** [vgist/dockerfiles#26]
It appears an update to alpine happened several weeks ago but it hasn't been pushed to Docker Hub for some reason.

**Comment by aieu** [comment]
It doesn't need to be updated, but as you wish

**Comment by elisimpson** [comment]
Thanks! FYI, the alpine update does fix a bug in curl:

https://github.com/curl/curl/issues/6312

This caused transmission to error when connecting to certain trackers
