### ISSUE TITLE
Username and password to connect via filezilla? 

### ISSUE THREAD

**Issue by echtelerp** [vgist/dockerfiles#4]
Hi vgist, 

I somehow can not connect to the ftp server. 
which password did you set to the user ftpuser? 
I somehow can't find it :-)

**Comment by zgist** [comment]
You should first run `docker exec -it pure-ftpd pure-pw useradd test -m -u ftpuser -d /home/ftpuser/test` to add virtual user

**Comment by echtelerp** [comment]
Thanks for the info, :-)
Is there a possibility to pass those in the container either on build or on run?

**Comment by zgist** [comment]
Good idea, I'll add the default user and password for the next update.

Before that, you can mount your custom pure-ftpd's database inside the container.

    /pureftpd:/etc/pureftpd

**Comment by echtelerp** [comment]
I Eddited the Dockerfile a little bit:

maybe you can get inspirations from it :-)
https://github.com/echtelerp/docker-environment/tree/master/arch_arm32v7/FTPserver
