### ISSUE TITLE
dnscrypt-proxy version update

### ISSUE THREAD

**Issue by adit-s** [vgist/dockerfiles#8]
Hello. I noticed the container is running dnscrypt-proxy version 1.9.5.
The latest version is 2.0.22 (https://github.com/jedisct1/dnscrypt-proxy/releases/).
Can the gists/dnscrypt-proxy be updated to the latest?

Thanks,
Adit S

**Comment by zgist** [comment]
https://github.com/vgist/dockerfiles/commit/b2ac1b0

**Comment by adit-s** [comment]
Thanks.
